### ISSUE TITLE
munged attribute names can break the app

### ISSUE THREAD

**Issue by Trott** [wmluke/grunt-inline-angular-templates#3]
Cheerio will change things like "data-ng-app" to "data-ngApp", breaking the Angular app in the process.

Workaround is to just use "ng-app" but ideally there would be an option to pass to cheerio/htmlparser/whatever such that it doesn't mess with the attribute names when `load()` + `html()` are called.

Hopefully there's an option to do that, but if it exists, I haven't found it yet.

I did write a test for this, though, over in this branch: https://github.com/Trott/grunt-inline-angular-templates/tree/no-munging-attribute-names

**Comment by Trott** [comment]
Looks like workaround for now would be to stick with cheerio 0.12.3.  https://github.com/MatthewMueller/cheerio/issues/284

**Comment by Trott** [comment]
Er, I mean 0.12.2.

**Comment by wmluke** [comment]
Hi @Trott,

Thanks for feedback.  

So it seems that a regression introduced with cheerio 0.12.3 is causing issues.

I haven't dug into npm's handling of transitive dependencies.  Based on your investigation, can you simply lock cheerio @ v0.12.2 in your package.json?

``` json
   "dependencies": {
        "cheerio": "0.12.2"
    }
```

I'm reluctant to cut a new release just to lock cheerio at 0.12.2, so I'm hoping this workaround flies until MatthewMueller/cheerio#284 is resolved.

Thanks again,
Luke

**Comment by Trott** [comment]
Yes, that seems like a sensible approach. Meanwhile, I've sent a pull request to fix the issue in cheerio:  https://github.com/MatthewMueller/cheerio/pull/296

**Comment by Trott** [comment]
They took the pull request, so hopefully when they release 0.12.4, you can just set that as the minimum version of cheerio in `package.json`.

**Comment by wmluke** [comment]
Thanks for digging into this, @Trott.  I appreciate it.  We'll leave this issue open, until cheerio releases 0.12.4.

**Comment by Trott** [comment]
cheerio 0.12.4 published! https://github.com/MatthewMueller/cheerio/issues/284#issuecomment-28310232

**Comment by wmluke** [comment]
@Trott, Thanks again for seeing this across the finish line. Mucho gracias.
